### ISSUE TITLE
Error on mobile : Can't set headers after they are sent

### ISSUE THREAD

**Issue by illusdidi** [brunnolou/streaming-room#19]
Hello ! 
I'm using streaming-room on Windows 10 and I love it !
But I have some troubles with the mobile version and I can't find the origin of the problem.
7 times ouf of 10, the livestream won't load on the mobile version, the player show : "The media playback was aborted due to a corruption problem or because the media used features your browser did not support", and the NodeJS console show : 

`Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (C:\Users\illus\Desktop\streaming-room-master\node_modules\send\index.js:390:13)
    at SendStream.send (C:\Users\illus\Desktop\streaming-room-master\node_modules\send\index.js:619:10)
    at onstat (C:\Users\illus\Desktop\streaming-room-master\node_modules\send\index.js:732:10)
    at FSReqWrap.oncomplete (fs.js:154:5)`

I guess it's a problem with sending headers twice or something like that in the webserver part. Do you have any idea ? Thanks :)

**Comment by illusdidi** [comment]
Ok I figured out the problem is with the protection of the '/videos' directory.
When I delete  ` app.use('/videos', protect);` from the webServer.js file, it works perfectly on mobile too, but the stream is now unprotected. Sooo it seems that on mobile the access to the playlist is denied, even if we're logged in. 
Signed cookies not sending to the server at one point ? 
🤔

**Comment by illusdidi** [comment]
On NodeJS the signed cookie "username" is "undefined" when I try to reach the stream on mobile. Any ideas why ? It's really annoying :/

**Comment by brunnolou** [comment]
Hey @illusdidi is your mobile device a Samsung?
