### ISSUE TITLE
no video

### ISSUE THREAD

**Issue by NHQ** [brunnolou/streaming-room#5]
I installed and successfully connected OBS to rtmp://localhost/live/live.  Is that the correct address?

In the terminal running this app, i eventually the following:
```
connect live/live
PUBLISH 
connect live
PLAY 
an error happened: ffmpeg exited with code 1: RTMP_ReadPacket, failed to read RTMP packet header
rtmp://localhost:1935/live/: Invalid data found when processing input
```

And at locahost:3000, inside the room, I get error "CANNOT GET VIDEO /videos/output.m3u8",  and there is no video display, only the load loop.

(and OBS seems to think it's connected and a-ok)

**Comment by brunnolou** [comment]
Hi thanks for using. 
Are you on windows?
Try to checkout to the branch `windows-config`

**Comment by NHQ** [comment]
I'm on Linux, Ubuntu 16.  
I just checked and I have latest ffmpeg.

**Comment by brunnolou** [comment]
Ok but try the branch still. I'll move to master later since it works on Mac OS too.
I'm using ffmpeg command directly there. 
Then let me know if it works.

**Comment by NHQ** [comment]
I'm not sure if this is the same error, but after switching to `window-config` this is what I got in the browser:

`"HLS playlist request error at URL: videos/output.m3u8"`

The terminal has not printed any error though, and OBS is ok.

**Comment by brunnolou** [comment]
So maybe it's converting. To confirm that go to `/public/videos` and see if the files are being created (`output.m3u8`, `*.mp4`)
Maybe you need to add writing permission?
Take in mind that the full converting process could have 1 minute delay depending on the machine.
Run the server, start publishing, wait a few seconds, check the videos folder, after a couple of videos, refresh the browser.

**Comment by NHQ** [comment]
It did not create directory `public/videos/` on install or upon startup. I
waited after connecting and checked, still nothing.  And no videos show up
there when I create the dir myself.  I checked permissions and ownership.

If you point me close in the code-base I'll inspect.

**Comment by brunnolou** [comment]
If is all good with OBS, only the conversion is failing. You can test the OBS streaming with vlc: rtmp:localhost/live/live 

The code is being converted to hls by executing the ffmpeg command directly. 
Here: https://github.com/brunnolou/streaming-room/blob/windows-config/src/rtmpToHLS.js
But It seems that the path to the video is wrong should be one folder back `../`

If still doesn't work try running the command on terminal and try different options:
https://github.com/brunnolou/streaming-room/blob/windows-config/src/command.sh

Let me know if it is working so I can fix and Merge to master. 
Thanks

**Comment by brunnolou** [comment]
@NHQ I did some changes regarding configurations and paths, please reset to master and try again. 
Let me know if that fixes or if you found a different solution. So I can close this issue.

**Comment by NHQ** [comment]
After update, when I connected OBS, stream-room printed "Wrong Stream key"
in red.  No videos in public/videos directory.

**Comment by brunnolou** [comment]
Cool it means that you should either use the default key "`live`" or you can specify a different one in the config file.
![image](https://user-images.githubusercontent.com/2729225/33013927-8a76c69e-cddd-11e7-81d9-236321c63814.png)

![image](https://user-images.githubusercontent.com/2729225/33013962-9b0e1ed0-cddd-11e7-855f-a1ac83229cd8.png)

**Comment by NHQ** [comment]
ah ok, I set that and got this error next:

ffmpeg error:  { Error: Command failed: ffmpeg  -i
rtmp:localhost/live/live  -maxrate 400k -bufsize 1835k -v verbose  -c:v
libx264  -c:a aac  -ac 1  -strict -2 -crf 18 -profile:v baseline -pix_fmt
yuv420p -flags -global_header -hls_time 10 -hls_list_size 6 -hls_wrap 10
-start_number 1 /home/programs/streaming-room/public/videos/output.m3u8
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg
developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1
--build-suffix=-ffmpeg --toolchain=hardened
--libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu
--cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping
--disable-decoder=libopenjpeg --disable-decoder=libschroedinger
--enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca
--enable-libcdio --enable-libflite --enable-libfontconfig
--enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm
--enable-libmodplug --enable-libmp3lame --enable-libopenjpeg
--enable-libopus --enable-libpulse --enable-librtmp
--enable-libschroedinger --enable-libshine --enable-libsnappy
--enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora
--enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack
--enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi
--enable-openal --enable-opengl --enable-x11grab --enable-libdc1394
--enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264
--enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Routing option strict to both codec and muxer layer
Parsing...
RTMP URL: No :// in url!
rtmp:localhost/live/live: Unknown error occurred

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ffmpeg  -i rtmp:localhost/live/live  -maxrate 400k -bufsize 1835k
-v verbose  -c:v libx264  -c:a aac  -ac 1  -strict -2 -crf 18 -profile:v
baseline -pix_fmt yuv420p -flags -global_header -hls_time 10 -hls_list_size
6 -hls_wrap 10 -start_number 1
/home/programs/streaming-room/public/videos/output.m3u8' }

**Comment by brunnolou** [comment]
@NHQ like the error said was a problem with the path `RTMP URL: No :// in url!`
I fixed from  `rtmp:localhost/…` to `rtmp://localhost/…`.
I was working on Mac but apparently not on Linux.

You can now pull from master. Let me know if it's working.

**Comment by NHQ** [comment]
Now I get this error, about 30 seconds after connecting OBS: 
```
RTMPSockBuf_Fill, recv returned -1. GetSockError(): 11 (Resource temporarily unavailable)
RTMP_ReadPacket, failed to read RTMP packet header
Invoking deleteStream
rtmp://localhost/live/live: Invalid data found when processing input

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ffmpeg  -i rtmp://localhost/live/live  -maxrate 400k -bufsize 1835k -v verbose  -c:v libx264  -c:a aac  -ac 1  -strict -2 -crf 18 -profile:v baseline -pix_fmt yuv420p -flags -global_header -hls_time 10 -hls_list_size 6 -hls_wrap 10 -start_number 1 /home/programs/streaming-room/public/videos/output.m3u8' }
```

**Comment by brunnolou** [comment]
I found out that the path can't be absolute so I updated the master branch.
Pull on master and try again. Maybe you need to reduce the video bitrate.
I have these settings in OBS output:
![image](https://user-images.githubusercontent.com/2729225/33487406-fe533014-d6a4-11e7-8f4f-c5b24f703949.png)

Try different settings in OBS.

I tested and it's working on Lubunto, Windows 10 and macOS Sierra.
Also instead of streaming from OBS, you can stream from the command line using FFmpeg command.

**Comment by brunnolou** [comment]
@NHQ I'm closing this. Check the latests versions. if you still have problems please reach out.

**Comment by NHQ** [comment]
today I updated to latest master, and got the same original error; no videos found in `public/videos/{video}`;  Obs seemed to connect okay at first;  I also tried a lower bitrate

did you merge that relative-path commit?  I see there's a different branch, and it's 1 commit ahead, 30 behind master

btw, if I'm not wrong, you should not commit `package-lock.json`, cuz it might screw with an install on different machine;  I had to manually install `/node_modules/@ffmpeg-install/ffmpeg`, to get latest master to work, and I think the lock file had something to do with it

**Comment by MaxBoehme** [comment]
Hello!

I have similar problem: no output.m3u8 gets generated :(

I have these seetings in OBS:
Server: rtmp://mywebsite.com/streaming-room/live/live
StreamKey: live

And these in the config.json
"input": "rtmp://mywebsite.com/streaming-room/live/",
"streamKey": "live"

I get successfully the messages:

CONNECT streaming-room/live/live
THEN ffmpeg does its magic with: (I logged this as well to see what's going on)
/rootdirectoryofmywebserver/nodevenv/streaming-room/backend/10/lib/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -i rtmp://mywebsite.com/streaming-room/live/live  -maxrate 400k -bufsize 1835k -v verbose  -c:v libx264  -c:a aac  -ac 1  -strict -2 -crf 18 -profile:v baseline -pix_fmt yuv420p -flags -global_header -hls_time 10 -hls_list_size 6 -hls_wrap 10 -start_number 1 public/videos/output.m3u8
PUBLISH  live
CONNECT streaming-room/live
PLAY   {"cmd":"play","transId":4,"cmdObj":null,"streamName":"live","start":-2000}

But still no video-files appear.

Any idea what its wrong or going on?

Thanks!

**Comment by brunnolou** [comment]
> Hello!
> 
> 
> 
> @brunnolou , I have similar problem: no output.m3u8 gets generated. :(
> 
> 
> 
> I have these settings in OBS:
> 
> _Server: rtmp://mywebsite.com/streaming-room/live/live
> 
> StreamKey: live_
> 
> 
> 
> And these in the config.json
> 
> _"input": "rtmp://mywebsite.com/streaming-room/live/",
> 
> "streamKey": "live"_
> 
> 
> 
> I get successfully the messages:
> 
> 
> 
> `CONNECT streaming-room/live/live`
> 
> THEN ffmpeg does its magic (I logged this as well to see what's going on):
> 
> ```
> 
> /rootdirectoryofmywebserver/nodevenv/streaming-room/backend/10/lib/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -i rtmp://mywebsite.com/streaming-room/live/live  -maxrate 400k -bufsize 1835k -v verbose  -c:v libx264  -c:a aac  -ac 1  -strict -2 -crf 18 -profile:v baseline -pix_fmt yuv420p -flags -global_header -hls_time 10 -hls_list_size 6 -hls_wrap 10 -start_number 1 public/videos/output.m3u8
> 
> PUBLISH  live
> 
> CONNECT streaming-room/live
> 
> PLAY   {"cmd":"play","transId":4,"cmdObj":null,"streamName":"live","start":-2000}
> 
> ```
> 
> 
> 
> But still no video-files appear.
> 
> 
> 
> Any idea what its wrong or going on?
> 
> 
> 
> Thanks!
> 
> 
> 
> EDIT
> 
> 
> 
> Apparently the connecting works fine and the configs are ok - but I get this ffmpeg-error- also it was working fine on localhost:
> 
> 
> 
> ```
> 
> App 1000233 output: FFmpeg error:
> 
> App 1000233 output: Error: Command failed: /home/mywebsite/nodevenv/streaming-room/backend/10/lib/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -i rtmp://mywebsite.com/streaming-room/live/live  -maxrate 400k -bufsize 1835k -v verbose  -max_muxing_queue_size 9999 -sc_threshold 0 -c:v libx264  -c:a aac  -ac 2 -b:a 128k -strict -2 -crf 18 -preset veryfast -profile:v baseline -pix_fmt yuv420p -flags -global_header -vf scale=1280:-2 -f hls -hls_time 10 -hls_list_size 6 -hls_wrap 10 -start_number 1 public/videos/output.m3u8
> 
> App 1000233 output: ffmpeg version N-87327-g18821e3ba1-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
> 
> App 1000233 output:   built with gcc 6.4.0 (Debian 6.4.0-5) 20170906
> 
> App 1000233 output:   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
> 
> App 1000233 output:   libavutil      55. 75.100 / 55. 75.100
> 
> App 1000233 output:   libavcodec     57.106.101 / 57.106.101
> 
> App 1000233 output:   libavformat    57. 82.100 / 57. 82.100
> 
> App 1000233 output:   libavdevice    57.  8.101 / 57.  8.101
> 
> App 1000233 output:   libavfilter     6.105.100 /  6.105.100
> 
> App 1000233 output:   libswscale      4.  7.103 /  4.  7.103
> 
> App 1000233 output:   libswresample   2.  8.100 /  2.  8.100
> 
> App 1000233 output:   libpostproc    54.  6.100 / 54.  6.100
> 
> App 1000233 output: Routing option strict to both codec and muxer layer
> 
> App 1000233 output: Parsing...
> 
> App 1000233 output: Parsed protocol: 0
> 
> App 1000233 output: Parsed host    : mywebsite.com
> 
> App 1000233 output: Parsed app     : streaming-room/live
> 
> App 1000233 output: RTMP_Connect1, ... connected, handshaking
> 
> App 1000233 output: HandShake: Type Answer   : 03
> 
> App 1000233 output: HandShake: Server Uptime : 1267037764
> 
> App 1000233 output: HandShake: FMS Version   : 0.0.0.0
> 
> App 1000233 output: HandShake: Handshaking finished....
> 
> App 1000233 output: RTMP_Connect1, handshaked
> 
> App 1000233 output: Invoking connect
> 
> App 1000233 output: HandleServerBW: server BW = 5000000
> 
> App 1000233 output: HandleClientBW: client BW = 5000000 2
> 
> App 1000233 output: HandleChangeChunkSize, received: chunk size change to 4096
> 
> App 1000233 output: RTMP_ClientPacket, received: invoke 190 bytes
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:           no-name., STRING:	_result>
> 
> App 1000233 output: Property: <Name:           no-name., NUMBER:	1.00>
> 
> App 1000233 output: Property: <Name:           no-name., OBJECT>
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:             fmsVer, STRING:	FMS/3,0,1,123>
> 
> App 1000233 output: Property: <Name:       capabilities, NUMBER:	31.00>
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: Property: <Name:           no-name., OBJECT>
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:              level, STRING:	status>
> 
> App 1000233 output: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
> 
> App 1000233 output: Property: <Name:        description, STRING:	Connection succeeded.>
> 
> App 1000233 output: Property: <Name:     objectEncoding, NUMBER:	0.00>
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: HandleInvoke, server invoking <_result>
> 
> App 1000233 output: HandleInvoke, received result for method call <connect>
> 
> App 1000233 output: sending ctrl. type: 0x0003
> 
> App 1000233 output: Invoking createStream
> 
> App 1000233 output: RTMP_ClientPacket, received: invoke 29 bytes
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:           no-name., STRING:	_result>
> 
> App 1000233 output: Property: <Name:           no-name., NUMBER:	2.00>
> 
> App 1000233 output: Property: NULL
> 
> App 1000233 output: Property: <Name:           no-name., NUMBER:	1.00>
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: HandleInvoke, server invoking <_result>
> 
> App 1000233 output: HandleInvoke, received result for method call <createStream>
> 
> App 1000233 output: SendPlay, seekTime=0, stopTime=0, sending play: live
> 
> App 1000233 output: Invoking play
> 
> App 1000233 output: sending ctrl. type: 0x0003
> 
> App 1000233 output: RTMP_ClientPacket, received: invoke 96 bytes
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:           no-name., STRING:	onStatus>
> 
> App 1000233 output: Property: <Name:           no-name., NUMBER:	0.00>
> 
> App 1000233 output: Property: NULL
> 
> App 1000233 output: Property: <Name:           no-name., OBJECT>
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:              level, STRING:	status>
> 
> App 1000233 output: Property: <Name:               code, STRING:	NetStream.Play.Start>
> 
> App 1000233 output: Property: <Name:        description, STRING:	Start live>
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: HandleInvoke, server invoking <onStatus>
> 
> App 1000233 output: HandleInvoke, onStatus: NetStream.Play.Start
> 
> App 1000233 output: RTMP_ClientPacket, received: notify 24 bytes
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:           no-name., STRING:	|RtmpSampleAccess>
> 
> App 1000233 output: Property: <Name:           no-name., BOOLEAN:	TRUE>
> 
> App 1000233 output: Property: <Name:           no-name., BOOLEAN:	TRUE>
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: HandleCtrl, received ctrl. type: 0, len: 6
> 
> App 1000233 output: HandleCtrl, Stream Begin 1
> 
> App 1000233 output: RTMP_ClientPacket, received: notify 383 bytes
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:           no-name., STRING:	onMetaData>
> 
> App 1000233 output: Property: <Name:           no-name., OBJECT>
> 
> App 1000233 output: (object begin)
> 
> App 1000233 output: Property: <Name:           duration, NUMBER:	0.00>
> 
> App 1000233 output: Property: <Name:           fileSize, NUMBER:	0.00>
> 
> App 1000233 output: Property: <Name:              width, NUMBER:	1280.00>
> 
> App 1000233 output: Property: <Name:             height, NUMBER:	720.00>
> 
> App 1000233 output: Property: <Name:       videocodecid, NUMBER:	7.00>
> 
> App 1000233 output: Property: <Name:      videodatarate, NUMBER:	400.00>
> 
> App 1000233 output: Property: <Name:          framerate, NUMBER:	30.00>
> 
> App 1000233 output: Property: <Name:       audiocodecid, NUMBER:	10.00>
> 
> App 1000233 output: Property: <Name:      audiodatarate, NUMBER:	128.00>
> 
> App 1000233 output: Property: <Name:    audiosamplerate, NUMBER:	48000.00>
> 
> App 1000233 output: Property: <Name:    audiosamplesize, NUMBER:	16.00>
> 
> App 1000233 output: Property: <Name:      audiochannels, NUMBER:	2.00>
> 
> App 1000233 output: Property: <Name:             stereo, BOOLEAN:	TRUE>
> 
> App 1000233 output: Property: <Name:                2.1, BOOLEAN:	FALSE>
> 
> App 1000233 output: Property: <Name:                3.1, BOOLEAN:	FALSE>
> 
> App 1000233 output: Property: <Name:                4.0, BOOLEAN:	FALSE>
> 
> App 1000233 output: Property: <Name:                4.1, BOOLEAN:	FALSE>
> 
> App 1000233 output: Property: <Name:                5.1, BOOLEAN:	FALSE>
> 
> App 1000233 output: Property: <Name:                7.1, BOOLEAN:	FALSE>
> 
> App 1000233 output: Property: <Name:            encoder, STRING:	obs-output module (libobs version 26.0.2)>
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: (object end)
> 
> App 1000233 output: Metadata:
> 
> App 1000233 output:   duration              0.00
> 
> App 1000233 output:   fileSize              0.00
> 
> App 1000233 output:   width                 1280.00
> 
> App 1000233 output:   height                720.00
> 
> App 1000233 output:   videocodecid          7.00
> 
> App 1000233 output:   videodatarate         400.00
> 
> App 1000233 output:   framerate             30.00
> 
> App 1000233 output:   audiocodecid          10.00
> 
> App 1000233 output:   audiodatarate         128.00
> 
> App 1000233 output:   audiosamplerate       48000.00
> 
> App 1000233 output:   audiosamplesize       16.00
> 
> App 1000233 output:   audiochannels         2.00
> 
> App 1000233 output:   stereo                TRUE
> 
> App 1000233 output:   2.1                   FALSE
> 
> App 1000233 output:   3.1                   FALSE
> 
> App 1000233 output:   4.0                   FALSE
> 
> App 1000233 output:   4.1                   FALSE
> 
> App 1000233 output:   5.1                   FALSE
> 
> App 1000233 output:   7.1                   FALSE
> 
> App 1000233 output:   encoder               obs-output module (libobs version 26.0.2)
> 
> App 1000233 output: [h264 @ 0x47df620] Reinit context to 1280x720, pix_fmt: yuv420p
> 
> App 1000233 output: Input #0, flv, from 'rtmp://mywebsite.com/streaming-room/live/live':
> 
> App 1000233 output:   Metadata:
> 
> App 1000233 output:     fileSize        : 0
> 
> App 1000233 output:     audiochannels   : 2
> 
> App 1000233 output:     2.1             : false
> 
> App 1000233 output:     3.1             : false
> 
> App 1000233 output:     4.0             : false
> 
> App 1000233 output:     4.1             : false
> 
> App 1000233 output:     5.1             : false
> 
> App 1000233 output:     7.1             : false
> 
> App 1000233 output:     encoder         : obs-output module (libobs version 26.0.2)
> 
> App 1000233 output:   Duration: 00:00:00.00, start: 24.044000, bitrate: N/A
> 
> App 1000233 output:     Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 131 kb/s
> 
> App 1000233 output:     Stream #0:1: Video: h264 (High), 1 reference frame, yuv420p(tv, bt709, progressive, left), 1280x720, 409 kb/s, 30 fps, 30 tbr, 1k tbn, 60 tbc
> 
> App 1000233 output: Stream mapping:
> 
> App 1000233 output:   Stream #0:1 -> #0:0 (h264 (native) -> h264 (libx264))
> 
> App 1000233 output:   Stream #0:0 -> #0:1 (aac (native) -> aac (native))
> 
> App 1000233 output: Press [q] to stop, [?] for help
> 
> App 1000233 output: [graph_1_in_0_0 @ 0x4b30fc0] tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x3
> 
> App 1000233 output: [h264 @ 0x4895120] Reinit context to 1280x720, pix_fmt: yuv420p
> 
> App 1000233 output: [h264 @ 0x48c6440] mmco: unref short failure
> 
> App 1000233 output: frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
> 
> frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
> 
> frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
> 
> frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
> 
> frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
> 
> [Parsed_scale_0 @ 0x51432e0] w:1280 h:-2 flags:'bicubic' interl:0
> 
> App 1000233 output: [graph 0 input from stream 0:1 @ 0x48e04a0] w:1280 h:720 pixfmt:yuv420p tb:1/1000 fr:30/1 sar:0/1 sws_param:flags=2
> 
> App 1000233 output: [Parsed_scale_0 @ 0x51432e0] w:1280 h:720 fmt:yuv420p sar:0/1 -> w:1280 h:720 fmt:yuv420p sar:0/1 flags:0x4
> 
> App 1000233 output: [libx264 @ 0x4803260] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> 
> App 1000233 output: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe inco
> 
> App 1000233 output: rrect parameters such as bit_rate, rate, width or height
> 
> App 1000233 output: [aac @ 0x47e0840] Qavg: 4795.730
> 
> App 1000233 output: [aac @ 0x47e0840] 2 frames left in the queue on closing
> 
> App 1000233 output: Invoking deleteStream
> 
> App 1000233 output: Conversion failed!
> 
> ```


Try upgrading `ffmpeg-installer/ffmpeg` to the latest version.
